### ISSUE TITLE
cant select file

### ISSUE THREAD

**Issue by X3NOOO** [Tigermouthbear/Theia#21]
when i click "select file" nothing happens
OS: Win 10 Pro 64 bit 20H2
Java version: java version "14.0.1" 2020-04-14

when i run this on vm with win 7 everything works

**Comment by Crystallinqq** [comment]
just select it lol

**Comment by JoeBidenOfficial** [comment]
> 
> 
> just select it lol

makes sense

**Comment by rand0m0User** [comment]
im having the same issue, so i ran the jar via command line, and hit the choose file and a long error appeared in the console: ```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/stage/DirectoryChooser
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)
        at java.desktop/java.awt.Component.isCoalesceEventsOverriden(Component.java:6316)
        at java.desktop/java.awt.Component$3.run(Component.java:6270)
        at java.desktop/java.awt.Component$3.run(Component.java:6268)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Component.checkCoalescing(Component.java:6267)
        at java.desktop/java.awt.Component.<init>(Component.java:6236)
        at java.desktop/java.awt.Container.<init>(Container.java:296)
        at java.desktop/javax.swing.JComponent.<init>(JComponent.java:598)
        at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:347)
        at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:295)
        at li.flor.nativejfilechooser.NativeJFileChooser.<init>(NativeJFileChooser.java:86)
        at dev.tigr.theia.gui.GUI$addElements$1.actionPerformed(GUI.kt:65)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6396)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.stage.DirectoryChooser
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 50 more``` (sorry in advanced if the codeblock does not embed)

**Comment by PATXS** [comment]
this is old af but just use an older java version, it'll work
